import {
  p1,
  p2,
  p3,
  p4,
  p5,
  p6
} from './router/index'
export const data = {
  products: [{
      _id: '1',
      name: 'Nike Fit Shirt',
      category: 'Shirts',
      image: p1,
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: p2,
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: p3,
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'High quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pants',
      category: 'Pants',
      image: p4,
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pants',
      category: 'Pants',
      image: p5,
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 3,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pants',
      category: 'Pants',
      image: p6,
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'High quality product',
    },
  ]
}